### ISSUE TITLE
There are several packages that cannot be cached, causing the installation of the pack to fail.

### ISSUE THREAD

**Issue by youwillbe** [stefan-hoeck/idris2-pack-db#137]
- base64
- buf-conn
- cont
- hash
- hmac
- http2
- lana
- pg
- pg-types
- racket-tcp
- scram
- sha
- string-search
- utf8
- web-server-racket
- web-server-racket-hello-world

<img width="1260" alt="image" src="https://github.com/stefan-hoeck/idris2-pack-db/assets/16474244/52acdadf-22a2-409b-ab44-d99b88c41c49">

<img width="1428" alt="image" src="https://github.com/stefan-hoeck/idris2-pack-db/assets/16474244/143fd28b-8764-431f-aead-3d675bfc43e8">

**Comment by stefan-hoeck** [comment]
Could you please give some information about the operating system you are using, as well as the version of your git installation? Also: Please provide the error messages as text not in form of a print screen.

**Comment by youwillbe** [comment]
My system : macOS Sonoma 14.2.1 (Intel)
git version: 2.43.0
error: "Can not visit 'https://git.sr.ht/~janus/...': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.sr.ht:443"

It seems that the packages starting with https://git.sr.ht/~janus are inaccessible. This address cannot be opened in the browser either.

**Comment by stefan-hoeck** [comment]
Thanks. I'll try and get in touch with the author of those packages on discord.

**Comment by buzden** [comment]
The problem is indeed more serious. This can occur not only because of server problems but also because of corporate or country-level restrictions on particular domains. Probably `pack` should give some workaround way to deal with such situations
